### PR TITLE
Fix: travis/tox

### PR DESCRIPTION
**Pull request by bertjwregeer**
Removed useless entries from `tox.ini`, and updated the `.travis.yml` file so that things start building again on Travis.

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM.  I'm sad to see `pypy3` fall by the wayside (it does have `u""` support, but is otherwise 3.2-compatible).

**Comment by mmerickel** [comment]
Yes unfortunately we've been dropping pypy3 on several projects because it broadcasts itself as 3.2 which we have dropped support for everywhere (because of pip). I know they just did a new release so when CI systems add support for it we can bring it back.

**Comment by bertjwregeer** [comment]
Looks like there was a PyPy 3.3 alpha that was released, once it is fully available I don't mind adding it back in.

**Comment by tseaver** [comment]
> Looks like there was a PyPy 3.3 alpha that was released, once it is fully available I don't mind adding it back in.

We've already dropped 3.3 support. :(

**Comment by tseaver** [comment]
Not quite sure why, exactly:  3.3 isn't problematic AFAICT.

**Comment by mmerickel** [comment]
3.3 is EOL next year but we were just talking in IRC about bringing it back for now if someone wants to re-add it. Pyramid deprecated it in 1.7 so that's the current benchmark.

http://docs.pylonsproject.org/projects/pyramid/en/latest/changes.html#deprecations

**Pull request merged**
